// On-chain presentation: addresses, transaction hashes, and an honest badge for
// what settlement is actually doing.
//
// The rule these all share: a hash is only ever offered as a link when the backend
// says it is a real chain transaction. In simulated mode the hash is random bytes,
// and linking it would send the viewer to an explorer 404 while implying the money
// moved. So simulated hashes render as plain text, labelled.
import type { CustomerSummary } from '@gigbridge/shared';
import { useSystemInfo, useIsOnChain, useExplorer } from '../lib/system.js';
import { shortHex } from '../lib/chain.js';

/**
 * What settlement is doing right now. Three states, and the third is the one that
 * matters: DEGRADED means real settlement was configured but the chain could not
 * be reached, so the backend fell back — the operator believes they are live and
 * they are not.
 */
export function SettlementBadge({ compact }: { compact?: boolean } = {}) {
  const info = useSystemInfo();
  if (!info) return null;

  if (info.degraded) {
    return (
      <span className="chip REJECT" title="SETTLEMENT_MODE=real is configured, but the chain was unreachable at boot, so payments are being simulated. Transaction hashes below are not real.">
        {compact ? 'SIMULATED (fallback)' : 'Settlement simulated — chain unreachable'}
      </span>
    );
  }
  if (info.settlementMode === 'real') {
    return (
      <span className="chip APPROVE" title={`Real transactions on ${info.chainName}. Hashes link to the block explorer.`}>
        {compact ? 'ON-CHAIN' : `On-chain · ${info.chainName}`}
      </span>
    );
  }
  return (
    <span className="chip PENDING" title="Settlement is simulated: the payment lifecycle is real, but transaction hashes are generated, not chain transactions.">
      {compact ? 'SIMULATED' : 'Settlement simulated'}
    </span>
  );
}

/** A transaction hash — a link when it is real, plain mono text when simulated. */
export function TxHash({ hash, short }: { hash: string | null | undefined; short?: boolean }) {
  const onChain = useIsOnChain();
  const explorer = useExplorer();
  if (!hash) return <span className="muted">—</span>;

  const text = short ? shortHex(hash, 10, 6) : hash;
  if (onChain && explorer) {
    return (
      <a className="mono" style={{ wordBreak: 'break-all' }} href={`${explorer}/tx/${hash}`} target="_blank" rel="noreferrer" title="View on the block explorer">
        {text} ↗
      </a>
    );
  }
  return (
    <span className="mono" style={{ wordBreak: 'break-all' }} title={onChain ? text : 'Simulated transaction hash — not a real chain transaction'}>
      {text}
      {!onChain && <span className="muted" style={{ fontSize: 11, marginLeft: 6 }}>simulated</span>}
    </span>
  );
}

/**
 * A settlement wallet. Links to the explorer on a real chain, and says when the
 * address is a throwaway the platform generated rather than an account someone
 * actually controls — the difference between a demo prop and a real destination.
 */
export function WalletAddress({
  address,
  source,
  canSign,
  short = true,
}: {
  address: string | null | undefined;
  source?: CustomerSummary['walletSource'];
  canSign?: boolean;
  short?: boolean;
}) {
  const explorer = useExplorer();
  const onChain = useIsOnChain();
  if (!address) return <span className="muted">— no wallet</span>;

  const text = short ? shortHex(address) : address;
  const body =
    onChain && explorer ? (
      <a className="mono" href={`${explorer}/address/${address}`} target="_blank" rel="noreferrer" title={address}>
        {text} ↗
      </a>
    ) : (
      <span className="mono" title={address}>{text}</span>
    );

  return (
    <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6, flexWrap: 'wrap' }}>
      {body}
      {source === 'GENERATED' && (
        <span className="muted" style={{ fontSize: 11 }} title="Generated by the platform for this demo — nobody holds its keys outside this server.">
          demo wallet
        </span>
      )}
      {source === 'PROVIDED' && canSign === false && (
        <span className="muted" style={{ fontSize: 11 }} title="An address with no private key: this party can be paid, but cannot sign a payment of its own.">
          receive-only
        </span>
      )}
    </span>
  );
}

/** How the off-ramp will deliver the money — the last mile, before it happens. */
export function DestinationTag({
  destination,
}: {
  destination: CustomerSummary['payoutDestination'] | undefined;
}) {
  if (!destination) {
    return (
      <span className="muted" style={{ fontSize: 12 }} title="No payout account: a payment would settle on-chain and then fail with nowhere to land.">
        no payout destination
      </span>
    );
  }
  return (
    <span style={{ fontSize: 12 }}>
      <b>{destination.method === 'UPI' ? 'UPI' : 'Bank'}</b>{' '}
      <span className="mono">{destination.masked}</span>{' '}
      <span className="muted">· {destination.currency}</span>
    </span>
  );
}
