// Settlement wallets — the one place an EVM account is resolved for a party.
//
// The platform used to mint `walletAddress` and `walletKey` as two INDEPENDENT
// randoms, so the address shown in the UI was not the account the backend signed
// with. That made the address decorative and forced real settlement to ignore it
// (see the old note in real-settlement.ts). Everything now goes through here, so
// the invariant holds: walletAddress is ALWAYS the address of walletKey.
//
// DEMO ONLY. The platform custodies the private key so the agent can settle
// without a wallet prompt. That is acceptable only because these are throwaway
// testnet accounts — never point this at an account holding real value.
import { privateKeyToAccount, generatePrivateKey } from 'viem/accounts';
import { EVM_ADDRESS_REGEX, EVM_PRIVATE_KEY_REGEX } from '@gigbridge/shared';

export type WalletSource = 'PROVIDED' | 'GENERATED';

export interface ResolvedWallet {
  address: string;
  /** Null when only an address was supplied: the party can be paid, not sign. */
  key: string | null;
  source: WalletSource;
}

const with0x = (v: string): `0x${string}` => (v.startsWith('0x') ? v : `0x${v}`) as `0x${string}`;

/** Checksummed address for a private key — the account that actually signs. */
export function addressOfKey(key: string): string {
  return privateKeyToAccount(with0x(key)).address;
}

const bad = (message: string) => Object.assign(new Error(message), { statusCode: 400 });

/**
 * Resolve the wallet for a party from what an operator supplied.
 *
 *   key only      -> address derived from it (can sign)
 *   address only  -> receive-only; no key is invented to sit beside it
 *   both          -> must agree, or the caller is told rather than one silently winning
 *   neither       -> a fresh generated pair (address derived from the key)
 */
export function resolveWallet(input: { walletAddress?: string; walletKey?: string }): ResolvedWallet {
  const suppliedAddress = input.walletAddress?.trim();
  const suppliedKey = input.walletKey?.trim();

  if (suppliedKey) {
    if (!EVM_PRIVATE_KEY_REGEX.test(suppliedKey)) throw bad('Private key must be 0x + 64 hex characters');
    let derived: string;
    try {
      derived = addressOfKey(suppliedKey);
    } catch {
      throw bad('That private key is not a valid EVM key');
    }
    if (suppliedAddress && suppliedAddress.toLowerCase() !== derived.toLowerCase()) {
      throw bad(`The private key belongs to ${derived}, not to the address you entered. Supply one or the other, or a matching pair.`);
    }
    return { address: derived, key: with0x(suppliedKey), source: 'PROVIDED' };
  }

  if (suppliedAddress) {
    if (!EVM_ADDRESS_REGEX.test(suppliedAddress)) throw bad('Wallet address must be 0x + 40 hex characters');
    // Receive-only. Deliberately no key: a random one here would recreate exactly
    // the address/key mismatch this module exists to remove.
    return { address: suppliedAddress, key: null, source: 'PROVIDED' };
  }

  const key = generatePrivateKey();
  return { address: addressOfKey(key), key, source: 'GENERATED' };
}

/**
 * Provenance of a stored wallet. Persisted on the User row rather than inferred:
 * a supplied account and a generated one can both carry a key, so there is nothing
 * in the address or key itself to tell them apart. Rows written before the column
 * existed are generated by definition.
 */
export function walletSourceOf(address: string | null, stored: string | null): WalletSource | null {
  if (!address) return null;
  return stored === 'PROVIDED' ? 'PROVIDED' : 'GENERATED';
}
