-- A settlement wallet is now either supplied by an operator (a real testnet
-- account they control) or generated by the platform. The UI states which, so a
-- throwaway demo address is never mistaken for an account that holds value.
-- Existing rows are generated by definition: they predate the ability to supply one.
ALTER TABLE "User" ADD COLUMN "walletSource" TEXT;
UPDATE "User" SET "walletSource" = 'GENERATED' WHERE "walletAddress" IS NOT NULL;
