// Export compiled artifacts from Foundry `out/` into shared/abis/ for the
// backend. Emits per contract:
//   - <name>.json  = { abi, bytecode }  (deploy.ts reads this via fs; committed
//                    so deploy-on-boot needs no forge in the container)
//   - <name>.ts    = the abi `as const` (viem typed calls in real-settlement)
// plus an index.ts. Run from repo root or contracts/:
//   node contracts/script/export-abis.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..', '..');
const contractsOut = resolve(repoRoot, 'contracts', 'out');
const outDir = resolve(repoRoot, 'shared', 'abis');

const CONTRACTS = ['MockUSDC', 'IdentityRegistry', 'EscrowVault', 'AuditAnchor'];
const camel = (s) => s[0].toLowerCase() + s.slice(1);

mkdirSync(outDir, { recursive: true });

const indexLines = [
  '// AUTO-GENERATED by contracts/script/export-abis.mjs — do not edit by hand.',
];
for (const name of CONTRACTS) {
  const artifact = JSON.parse(
    readFileSync(resolve(contractsOut, `${name}.sol`, `${name}.json`), 'utf8'),
  );
  const abi = artifact.abi;
  const bytecode = artifact.bytecode?.object ?? '0x';
  writeFileSync(resolve(outDir, `${name}.json`), JSON.stringify({ abi, bytecode }, null, 2) + '\n');
  writeFileSync(
    resolve(outDir, `${name}.ts`),
    `// AUTO-GENERATED by contracts/script/export-abis.mjs — do not edit by hand.\n` +
      `export const ${camel(name)}Abi = ${JSON.stringify(abi)} as const;\n`,
  );
  indexLines.push(`export { ${camel(name)}Abi } from './${name}.js';`);
}
writeFileSync(resolve(outDir, 'index.ts'), indexLines.join('\n') + '\n');

console.log(`Exported ${CONTRACTS.length} ABIs to shared/abis/`);
